import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const lexend = Lexend({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>
        <StoreProvider>
          {children}
          {modal}
        </StoreProvider>
      </body>
    </html>
  );
}
